export type AppColors = {
  primary: string;
  primaryDark: string;
  primarySurface: string;
  primarySurfaceAlt: string;
  primaryBorder: string;
  successSurface: string;
  warningSurface: string;
  infoSurface: string;
  background: string;
  backgroundMuted: string;
  surface: string;
  border: string;
  surfaceAlt: string;
  divider: string;
  trackMuted: string;
  success: string;
  gray50: string;
  gray100: string;
  gray200: string;
  gray300: string;
  gray400: string;
  gray500: string;
  gray600: string;
  gray700: string;
  gray800: string;
  gray900: string;
  overlay: string;
  shadow: string;
  text: string;
  textMuted: string;
  textSubtle: string;
  label: string;
  placeholder: string;
  error: string;
  errorSurface: string;
  errorText: string;
  white: string;
  onPrimary: string;
  onPrimaryMuted: string;
  onPrimarySubtle: string;
  primaryDisabled: string;
  glassSurface: string;
  glassBorder: string;
  glassBorderStrong: string;
  dotInactive: string;
  onPrimaryFaint: string;
  onPrimaryFaint70: string;
  onPrimaryFaint80: string;
  avatarSurface: string;
  chipMuted: string;
  chipMutedText: string;
  chipPrimarySurface: string;
  textBody: string;
  textFaint: string;
  backgroundSoft: string;
  radioBorder: string;
  onPrimaryHeaderSub: string;
  warningBannerBg: string;
  warningBannerBorder: string;
  warningBannerText: string;
  warningBannerArrow: string;
  infoBannerBorder: string;
  textMutedLight: string;
  selectedSurface: string;
  borderMuted: string;
  activeBadgeSurface: string;
  successStrong: string;
  successText: string;
  timelineTrack: string;
  dividerSoft: string;
  dangerBorder: string;
  dangerSurface: string;
  borderSubtle: string;
  timelineDotPast: string;
  timelineDotFuture: string;
  exploreOverlay: string;
  glassTag: string;
  backgroundFaint: string;
  onPrimaryFaint20: string;
  onPrimaryFaint55: string;
  onPrimaryFaint60: string;
  activeDotGreen: string;
  textFaintBlue: string;
  timelineTrackLight: string;
  feeTextOrange: string;
  overlay45: string;
  hintSurface: string;
  textSlate: string;
  pinBorderPast: string;
  pinBgPast: string;
  surfaceFaded92: string;
  surfaceFaded85: string;
  routePast: string;
};

export const lightColors: AppColors = {
  primary: '#023665',
  primaryDark: '#023665',
  primarySurface: '#EEF2FF',
  primarySurfaceAlt: '#F0F4FF',
  primaryBorder: '#C7D2FE',
  successSurface: '#F0FDF4',
  warningSurface: '#FFF7ED',
  infoSurface: '#F5F3FF',
  background: '#ffffff',
  backgroundMuted: '#F6F8FC',
  surface: '#f8f9fb',
  border: '#e2e8f0',
  surfaceAlt: '#f8fafc',
  divider: '#f1f5f9',
  trackMuted: '#dddddd',
  success: '#22c55e',
  gray50: '#F9FAFB',
  gray100: '#F3F4F6',
  gray200: '#E5E7EB',
  gray300: '#D1D5DB',
  gray400: '#9CA3AF',
  gray500: '#6B7280',
  gray600: '#666666',
  gray700: '#374151',
  gray800: '#3f3f40',
  gray900: '#111827',
  overlay: 'rgba(0,0,0,0.4)',
  shadow: '#000000',
  text: '#1a1a1a',
  textMuted: '#4a5568',
  textSubtle: '#8a9ab0',
  label: '#4a5568',
  placeholder: '#aab',
  error: '#EF4444',
  errorSurface: '#fff0f0',
  errorText: '#c0392b',
  white: '#ffffff',
  onPrimary: '#ffffff',
  onPrimaryMuted: '#e0e5ed',
  onPrimarySubtle: '#c7d2fe',
  primaryDisabled: '#93adc8',
  glassSurface: 'rgba(255,255,255,0.15)',
  glassBorder: 'rgba(255,255,255,0.25)',
  glassBorderStrong: 'rgba(255,255,255,0.4)',
  dotInactive: 'rgba(255,255,255,0.3)',
  onPrimaryFaint: 'rgba(255,255,255,0.65)',
  onPrimaryFaint70: 'rgba(255,255,255,0.7)',
  onPrimaryFaint80: 'rgba(255,255,255,0.8)',
  avatarSurface: '#eef2f7',
  chipMuted: '#f1f5f9',
  chipMutedText: '#6b7280',
  chipPrimarySurface: '#e8f0fe',
  textBody: '#333333',
  textFaint: '#444444',
  backgroundSoft: '#f5f5f5',
  radioBorder: '#cccccc',
  onPrimaryHeaderSub: '#d4d4d4',
  warningBannerBg: '#fff3cd',
  warningBannerBorder: '#ffeaa0',
  warningBannerText: '#7a5f00',
  warningBannerArrow: '#c0a000',
  infoBannerBorder: '#c5d4f8',
  textMutedLight: '#888888',
  selectedSurface: '#f0f4ff',
  borderMuted: '#c0ccd8',
  activeBadgeSurface: '#e8f5e9',
  successStrong: '#43a047',
  successText: '#2e7d32',
  timelineTrack: '#e0e8f0',
  dividerSoft: '#f0f4f8',
  dangerBorder: '#fca5a5',
  dangerSurface: '#fff5f5',
  borderSubtle: '#e8edf3',
  timelineDotPast: '#9aa4b2',
  timelineDotFuture: '#4a90d9',
  exploreOverlay: 'rgba(0,20,60,0.52)',
  glassTag: 'rgba(255,255,255,0.18)',
  backgroundFaint: '#f9f9f9',
  onPrimaryFaint20: 'rgba(255,255,255,0.2)',
  onPrimaryFaint55: 'rgba(255,255,255,0.55)',
  onPrimaryFaint60: 'rgba(255,255,255,0.6)',
  activeDotGreen: '#4ade80',
  textFaintBlue: '#aab4c2',
  timelineTrackLight: '#dde4ee',
  feeTextOrange: '#c2410c',
  overlay45: 'rgba(0,0,0,0.45)',
  hintSurface: '#e8f0fa',
  textSlate: '#4B5563',
  pinBorderPast: '#c8ced8',
  pinBgPast: '#f0f2f5',
  surfaceFaded92: 'rgba(255,255,255,0.92)',
  surfaceFaded85: 'rgba(255,255,255,0.85)',
  routePast: 'rgba(160,168,180,0.22)',
};

export const colors = lightColors;
