import { StyleSheet } from 'react-native';
import { AppColors } from '@/src/theme';

export const styles = (colors: AppColors) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.primary },
    content: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 32,
    },
    hero: {
      width: 120,
      height: 120,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 24,
    },
    heroDecoration: { position: 'absolute' },
    heroBadge: {
      width: 96,
      height: 96,
      borderRadius: 48,
      backgroundColor: colors.white,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.shadow,
      shadowOpacity: 0.2,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 6 },
      elevation: 6,
    },
    dots: { flexDirection: 'row', gap: 8, marginBottom: 20 },
    dot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.dotInactive,
    },
    dotActive: { backgroundColor: colors.white, width: 24 },
    retakeBadge: {
      marginBottom: 20,
      backgroundColor: colors.glassSurface,
      borderRadius: 20,
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderWidth: 1,
      borderColor: colors.glassBorder,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    retakeBadgeText: { color: colors.white, fontSize: 13, fontFamily: 'Inter-Medium' },
    textBlock: { alignSelf: 'stretch' },
    title: {
      fontSize: 28,
      fontFamily: 'Inter-Bold',
      color: colors.white,
      marginBottom: 12,
    },
    subtitle: {
      fontSize: 15,
      color: colors.onPrimarySubtle,
      lineHeight: 24,
    },
    buttons: { paddingHorizontal: 32, paddingBottom: 48, gap: 12 },
    primaryButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      backgroundColor: colors.white,
      borderRadius: 28,
      padding: 16,
    },
    primaryButtonText: { color: colors.primaryDark, fontFamily: 'Inter-Bold', fontSize: 16 },
    secondaryButton: {
      borderRadius: 28,
      padding: 16,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.glassBorderStrong,
      minHeight: 52,
      justifyContent: 'center',
    },
    secondaryButtonText: { color: colors.white, fontSize: 16 },
  });
